// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsYlBOUOUcW0LjfEwlqUGUZ-BTUvJuclg',
    appId: '1:970724701455:web:4ac90425871c53ddd17a7a',
    messagingSenderId: '970724701455',
    projectId: 'petrescues-af633',
    authDomain: 'petrescues-af633.firebaseapp.com',
    storageBucket: 'petrescues-af633.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCl8-yKY1DiwL7-8MQAdghJvFkCQjXVBn8',
    appId: '1:970724701455:android:6a4f5ed801f9114ed17a7a',
    messagingSenderId: '970724701455',
    projectId: 'petrescues-af633',
    storageBucket: 'petrescues-af633.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSdNDhz9uUkO7PVqIBfTIYKDUZ9p_BDHc',
    appId: '1:970724701455:ios:0b4dd724d39110bbd17a7a',
    messagingSenderId: '970724701455',
    projectId: 'petrescues-af633',
    storageBucket: 'petrescues-af633.appspot.com',
    iosBundleId: 'com.example.petRescues',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSdNDhz9uUkO7PVqIBfTIYKDUZ9p_BDHc',
    appId: '1:970724701455:ios:0b4dd724d39110bbd17a7a',
    messagingSenderId: '970724701455',
    projectId: 'petrescues-af633',
    storageBucket: 'petrescues-af633.appspot.com',
    iosBundleId: 'com.example.petRescues',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsYlBOUOUcW0LjfEwlqUGUZ-BTUvJuclg',
    appId: '1:970724701455:web:c8b0da9094f10a45d17a7a',
    messagingSenderId: '970724701455',
    projectId: 'petrescues-af633',
    authDomain: 'petrescues-af633.firebaseapp.com',
    storageBucket: 'petrescues-af633.appspot.com',
  );
}
